#pragma once

#define LOG_ENABLE_MOUSEMOVEMENT_CORE 0
#define LOG_ENABLE_MOUSEMOVEMENT_IMU 0
#define LOG_ENABLE_MOUSEMOVEMENT_TOUCH 0
#define LOG_ENABLE_MOUSEMOVEMENT_TELEMETRY 0
#define LOG_ENABLE_SIP_PUFF 1
#define LOG_ENABLE_JOYSTICK_KEYBOARD 1
